export const rawGames = [
  {
    "game_number": 1,
    "game_string": "1. Morrison vs Wallace - Windells",
    "game_date": null,
    "game_players": ["Noah Morrison", "Noah Wallace"],
    "game_location": "Windells",
    "game_tricks": [
      {
        "set_number": 1,
        "setter": "noah wallace",
        "offense_land": true,
        "defense_land": true,
        "terrain": "jump",
        "trick_string": "Left Rodeo 9, Safety",
        "line": false,
        "line_number": null,
        "air_direction": "Left",
        "air_axis": "rodeo",
        "air_rotation": 900,
        "air_grab": "Safety",
        "rail_direction": null,
        "rail_in": null,
        "rail_on": null,
        "rail_out": null,
        "type_of_rail": null,
        "not_sure": null
      },
      {
        "set_number": 2,
        "setter": "Noah Wallace",
        "offense_land": true,
        "defense_land": true,
        "terrain": "Jump",
        "trick_string": "R Cork 9, Japan",
        "line": null,
        "rebate": false,
        "air_direction": "Right",
        "air_axis": "Cork",
        "air_rotation": 900,
        "air_grab": "Japan",
        "rail_direction": null,
        "rail_in": null,
        "rail_on": null,
        "rail_out": null,
        "type_of_rail": null,
        "not_sure": null
      },
      {
        "set_number": 3,
        "setter": "Noah Wallace",
        "offense_land": true,
        "defense_land": true,
        "terrain": "Jump",
        "trick_string": "SWL Cork 9, Stale",
        "line": null,
        "rebate": false,
        "air_direction": "Switch Left",
        "air_axis": "Switch Cork",
        "air_rotation": 900,
        "air_grab": "Stale",
        "rail_direction": null,
        "rail_in": null,
        "rail_on": null,
        "rail_out": null,
        "type_of_rail": null,
        "not_sure": null
      },
      {
        "set_number": 4,
        "setter": "Noah Wallace",
        "offense_land": false,
        "defense_land": true,
        "terrain": "QP",
        "trick_stri": "L Cork7, Safety",
        "line": null,
        "rebate": false,
        "air_direction": "Left",
        "air_axis": "Dub Cork",
        "air_rotation": 720,
        "air_grab": "Safety",
        "rail_direction": null,
        "rail_in": null,
        "rail_on": null,
        "rail_out": null,
        "type_of_rail": null,
        "not_sure": null
      },
      {
        "set_number": 5,
        "setter": "Noah Morrison",
        "offense_land": true,
        "defense_land": false,
        "terrain": "Jump",
        "trick_string": "SWL Dub Cork 9",
        "line": null,
        "rebate": false,
        "air_direction": "Switch Left",
        "air_axis": "Switch Dub Cork",
        "air_rotation": 900,
        "air_grab": null,
        "rail_direction": null,
        "rail_in": null,
        "rail_on": null,
        "rail_out": null,
        "type_of_rail": null,
        "not_sure": null
      },
      {
        "set_number": 6,
        "setter": "Noah Morrison",
        "offense_land": true,
        "defense_land": true,
        "terrain": "Jump",
        "trick_string": "L Cork 9, Nose to Lead Stale",
        "line": null,
        "rebate": false,
        "air_direction": "Left",
        "air_axis": "Cork",
        "air_rotation": 900,
        "air_grab": "Nose to Lead Stale",
        "rail_direction": null,
        "rail_in": null,
        "rail_on": null,
        "rail_out": null,
        "type_of_rail": null,
        "not_sure": null
      },
      {
        "set_number": 7,
        "setter": "Noah Morrison",
        "offense_land": true,
        "defense_land": false,
        "terrain": "Jump",
        "trick_string": "L Dub Cork 10, Mute to Japan",
        "line": null,
        "rebate": false,
        "air_direction": "Left",
        "air_axis": "Dub Cork",
        "air_rotation": 1080,
        "air_grab": "Mute to Japan",
        "rail_direction": null,
        "rail_in": null,
        "rail_on": null,
        "rail_out": null,
        "type_of_rail": null,
        "not_sure": null
      },
      {
        "set_number": 8,
        "setter": "Noah Morrison",
        "offense_land": false,
        "defense_land": false,
        "terrain": "Rail",
        "trick_stri": "L NB2, B2",
        "line": null,
        "rebate": false,
        "air_direction": null,
        "air_axis": null,
        "air_rotation": null,
        "air_grab": null,
        "rail_direction": "Left",
        "rail_in": "NB2",
        "rail_on": null,
        "rail_out": "B2",
        "type_of_rail": "Down Rail",
        "not_sure": null
      },
      {
        "set_number": 9,
        "setter": "Noah Wallace",
        "offense_land": false,
        "defense_land": false,
        "terrain": "Jump",
        "trick_stri": "R Rodeo 9",
        "line": null,
        "rebate": false,
        "air_direction": "Right",
        "air_axis": "Rodeo",
        "air_rotation": 900,
        "air_grab": null,
        "rail_direction": null,
        "rail_in": null,
        "rail_on": null,
        "rail_out": null,
        "type_of_rail": null,
        "not_sure": null
      },
      {
        "set_number": 10,
        "setter": "Noah Morrison",
        "offense_land": true,
        "defense_land": false,
        "terrain": "Jump",
        "trick_string": "L Dub 12 Blunt",
        "line": null,
        "rebate": false,
        "air_direction": "Left",
        "air_axis": "Dub Cork",
        "air_rotation": 1260,
        "air_grab": "Blunt",
        "rail_direction": null,
        "rail_in": null,
        "rail_on": null,
        "rail_out": null,
        "type_of_rail": null,
        "not_sure": null
      },
      {
        "set_number": 11,
        "setter": "Noah Morrison",
        "offense_land": false,
        "defense_land": false,
        "terrain": "Rail",
        "trick_stri": "FS, B4",
        "line": null,
        "rebate": false,
        "air_direction": null,
        "air_axis": null,
        "air_rotation": null,
        "air_grab": null,
        "rail_direction": null,
        "rail_in": null,
        "rail_on": "FS",
        "rail_out": "B4",
        "type_of_rail": "Flat Rail",
        "not_sure": null
      },
      {
        "set_number": 12,
        "setter": "Noah Wallace",
        "offense_land": true,
        "defense_land": false,
        "terrain": "QP",
        "trick_string": "AO Handplant to SW",
        "line": null,
        "rebate": false,
        "air_direction": "AO",
        "air_axis": "Handplant",
        "air_rotation": null,
        "air_grab": null,
        "rail_direction": null,
        "rail_in": null,
        "rail_on": null,
        "rail_out": null,
        "type_of_rail": null,
        "not_sure": null
      },
      {
        "set_number": 13,
        "setter": "Noah Wallace",
        "offense_land": true,
        "defense_land": false,
        "terrain": "Jump",
        "trick_string": "R Rodeo 9",
        "line": null,
        "rebate": false,
        "air_direction": "Right",
        "air_axis": "Rodeo",
        "air_rotation": 900,
        "air_grab": null,
        "rail_direction": null,
        "rail_in": null,
        "rail_on": null,
        "rail_out": null,
        "type_of_rail": null,
        "not_sure": null
      },
      {
        "set_number": 14,
        "setter": "Noah Wallace",
        "offense_land": true,
        "defense_land": false,
        "terrain": "QP",
        "trick_string": "R Dub 10",
        "line": null,
        "rebate": false,
        "air_direction": "Right",
        "air_axis": "Dub Cork",
        "air_rotation": 1080,
        "air_grab": null,
        "rail_direction": null,
        "rail_in": null,
        "rail_on": null,
        "rail_out": null,
        "type_of_rail": null,
        "not_sure": null
      },
      {
        "set_number": 15,
        "setter": "Noah Wallace",
        "offense_land": true,
        "defense_land": true,
        "terrain": "QP",
        "trick_string": "L Cork 9",
        "line": null,
        "rebate": false,
        "air_direction": "Left",
        "air_axis": "Cork",
        "air_rotation": 900,
        "air_grab": null,
        "rail_direction": null,
        "rail_in": null,
        "rail_on": null,
        "rail_out": null,
        "type_of_rail": null,
        "not_sure": null
      },
      {
        "set_number": 16,
        "setter": "Noah Wallace",
        "offense_land": true,
        "defense_land": true,
        "terrain": "Jump",
        "trick_string": 180,
        "line": "Line 1",
        "rebate": false,
        "air_direction": null,
        "air_axis": null,
        "air_rotation": 180,
        "air_grab": null,
        "rail_direction": null,
        "rail_in": null,
        "rail_on": null,
        "rail_out": null,
        "type_of_rail": null,
        "not_sure": null
      },
      {
        "set_number": 17,
        "setter": "Noah Wallace",
        "offense_land": true,
        "defense_land": false,
        "terrain": "Rail",
        "trick_string": "SWL T2, F2",
        "line": "Line 1",
        "rebate": false,
        "air_direction": null,
        "air_axis": null,
        "air_rotation": null,
        "air_grab": null,
        "rail_direction": "Switch Left",
        "rail_in": "Switch Tails 270",
        "rail_on": null,
        "rail_out": "F2",
        "type_of_rail": "Down Rail",
        "not_sure": null
      },
      {
        "set_number": 18,
        "setter": "Noah Wallace",
        "offense_land": true,
        "defense_land": true,
        "terrain": "Rail",
        "trick_string": "F4",
        "line": "Line 2",
        "rebate": false,
        "air_direction": null,
        "air_axis": null,
        "air_rotation": null,
        "air_grab": null,
        "rail_direction": null,
        "rail_in": null,
        "rail_on": null,
        "rail_out": "F4",
        "type_of_rail": "Flat Rail",
        "not_sure": null
      },
      {
        "set_number": 19,
        "setter": "Noah Wallace",
        "offense_land": false,
        "defense_land": false,
        "terrain": "QP",
        "trick_stri": "AO Flat 5",
        "line": "Line 2",
        "rebate": false,
        "air_direction": null,
        "air_axis": "Flat",
        "air_rotation": 540,
        "air_grab": null,
        "rail_direction": null,
        "rail_in": null,
        "rail_on": null,
        "rail_out": null,
        "type_of_rail": null,
        "not_sure": null
      },
      {
        "set_number": 20,
        "setter": "Noah Morrison",
        "offense_land": false,
        "defense_land": true,
        "terrain": "Jump",
        "trick_stri": "SW Dub 10, Japan to Blunt",
        "line": null,
        "rebate": false,
        "air_direction": "Switch Left",
        "air_axis": "Switch Dub Cork",
        "air_rotation": 1080,
        "air_grab": "Japan to Blunt",
        "rail_direction": null,
        "rail_in": null,
        "rail_on": null,
        "rail_out": null,
        "type_of_rail": null,
        "not_sure": null
      },
      {
        "set_number": 21,
        "setter": "Noah Morrison - (Rebate - Morrison)",
        "offense_land": "NA",
        "defense_land": false,
        "terrain": "Jump",
        "trick_stri": "SW Dub 10, Japan to Blunt - Rebate",
        "line": null,
        "rebate": true,
        "air_direction": "Switch Left",
        "air_axis": "Switch Dub Cork",
        "air_rotation": 1080,
        "air_grab": "Japan to Blunt",
        "rail_direction": null,
        "rail_in": null,
        "rail_on": null,
        "rail_out": null,
        "type_of_rail": null,
        "not_sure": null
      }
    ]
  }

]
